const USER_LOGIN = ((( 'Andrei' )));

const CONFIG_DEBUG_MODE = ((( true )));

const CONFIG_DEBUG_MODE_LOADER = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_OPERATIONS = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_SETTINGS = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_CURRENCY = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_ACCOUNTS = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_ABOUT = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_MAIN = ((( false )));

const CONFIG_DEBUG_MODE_DATA_LOADING = ((( false )));

const CONFIG_DEBUG_MODE_DELETE_CONFIRMATION = ((( false )));

const CONFIG_DEBUG_MODE_DATE_RANGE_CHART = ((( false )));

const CONFIG_DEBUG_MODE_OPERATION_CARD = ((( false )));

const CONFIG_DEBUG_MODE_ACCOUNT_CARD = ((( false )));

const CONFIG_DEBUG_MODE_OPERATION_CATEGORY_CARD = ((( false )));

const CONFIG_DEBUG_MODE_CURRENCY_LIST_CARD = ((( false )));

const CONFIG_DEBUG_MODE_SMART_GRID = ((( false )));

const CONFIG_DEBUG_MODE_SMART_GRID_UTILS = ((( false )));

const CONFIG_DEBUG_MODE_BUTTON = ((( false )));

const CONFIG_DEBUG_MODE_BUTTON_LABEL = ((( false )));

const CONFIG_DEBUG_MODE_NUMBER_INPUT = ((( false )));

const CONFIG_DEBUG_MODE_EXCEL_TMPL = ((( false )));

const CONFIG_DEBUG_MODE_EXCEL_CONVERTER = ((( false )));

const CONFIG_DEBUG_MODE_CURRENCY_CALCULATOR = ((( false )));

const CONFIG_DEBUG_MODE_ACCOUNT_FILTER_PANEL = ((( false )));

const CONFIG_DEBUG_MODE_CLOCK= ((( false )));

const CONFIG_DEBUG_MODE_F_DATA = ((( false )));

const CONFIG_DEBUG_MODE_F_CURRENCY = ((( false )));

const CONFIG_UI_MODE_TIMEOUT = ((( 500 )));

export {
    USER_LOGIN,
    CONFIG_DEBUG_MODE,
    CONFIG_DEBUG_MODE_LOADER,
    CONFIG_DEBUG_MODE_PAGE_OPERATIONS,
    CONFIG_DEBUG_MODE_PAGE_SETTINGS,
    CONFIG_DEBUG_MODE_PAGE_CURRENCY,
    CONFIG_DEBUG_MODE_PAGE_ACCOUNTS,
    CONFIG_DEBUG_MODE_PAGE_ABOUT,
    CONFIG_DEBUG_MODE_PAGE_MAIN,
    CONFIG_DEBUG_MODE_DATA_LOADING,
    CONFIG_DEBUG_MODE_DELETE_CONFIRMATION,
    CONFIG_DEBUG_MODE_DATE_RANGE_CHART,
    CONFIG_DEBUG_MODE_OPERATION_CARD,
    CONFIG_DEBUG_MODE_ACCOUNT_CARD,
    CONFIG_DEBUG_MODE_OPERATION_CATEGORY_CARD,
    CONFIG_DEBUG_MODE_CURRENCY_LIST_CARD,
    CONFIG_DEBUG_MODE_SMART_GRID,
    CONFIG_DEBUG_MODE_SMART_GRID_UTILS,
    CONFIG_DEBUG_MODE_BUTTON,
    CONFIG_DEBUG_MODE_BUTTON_LABEL,
    CONFIG_DEBUG_MODE_NUMBER_INPUT,
    CONFIG_DEBUG_MODE_EXCEL_TMPL,
    CONFIG_DEBUG_MODE_EXCEL_CONVERTER,
    CONFIG_DEBUG_MODE_CURRENCY_CALCULATOR,
    CONFIG_DEBUG_MODE_ACCOUNT_FILTER_PANEL,
    CONFIG_DEBUG_MODE_CLOCK,

    CONFIG_DEBUG_MODE_F_DATA,
    CONFIG_DEBUG_MODE_F_CURRENCY,

    CONFIG_UI_MODE_TIMEOUT,
};