const USER_LOGIN = ((( 'Andrei' )));

const CONFIG_DEBUG_MODE = ((( true )));

const CONFIG_DEBUG_MODE_PAGE_OPERATIONS = ((( false )));

const CONFIG_DEBUG_MODE_PAGE_SETTINGS = ((( true )));

const CONFIG_DEBUG_MODE_DATA_LOADING = ((( false )));

const CONFIG_DEBUG_MODE_DELETE_CONFIRMATION = ((( false )));

const CONFIG_DEBUG_MODE_OPERATION_CARD = ((( false )));

const CONFIG_DEBUG_MODE_ACCOUNT_CARD = ((( true )));

const CONFIG_DEBUG_MODE_OPERATION_CATEGORY_CARD = ((( true )));

// const CONFIG_DEBUG_MODE_TABLE = ((( true )));

const CONFIG_DEBUG_MODE_SMART_GRID = ((( false )));

const CONFIG_DEBUG_MODE_SMART_GRID_UTILS = ((( false )));

const CONFIG_DEBUG_MODE_BUTTON = ((( false )));

const CONFIG_DEBUG_MODE_BUTTON_LABEL = ((( false )));

const CONFIG_DEBUG_MODE_NUMBER_INPUT = ((( false )));

const CONFIG_DEBUG_MODE_EXCEL_TMPL = ((( false )));

const CONFIG_DEBUG_MODE_EXCEL_CONVERTER = ((( false )));

const CONFIG_DEBUG_MODE_F_DATA = ((( false )));

const CONFIG_UI_MODE_TIMEOUT = ((( 500 )));

export {
    USER_LOGIN,
    CONFIG_DEBUG_MODE,
    CONFIG_DEBUG_MODE_PAGE_OPERATIONS,
    CONFIG_DEBUG_MODE_PAGE_SETTINGS,
    CONFIG_DEBUG_MODE_DATA_LOADING,
    CONFIG_DEBUG_MODE_DELETE_CONFIRMATION,
    CONFIG_DEBUG_MODE_OPERATION_CARD,
    CONFIG_DEBUG_MODE_ACCOUNT_CARD,
    CONFIG_DEBUG_MODE_OPERATION_CATEGORY_CARD,
    // CONFIG_DEBUG_MODE_TABLE,
    CONFIG_DEBUG_MODE_SMART_GRID,
    CONFIG_DEBUG_MODE_SMART_GRID_UTILS,
    CONFIG_DEBUG_MODE_BUTTON,
    CONFIG_DEBUG_MODE_BUTTON_LABEL,
    CONFIG_DEBUG_MODE_NUMBER_INPUT,
    CONFIG_DEBUG_MODE_EXCEL_TMPL,
    CONFIG_DEBUG_MODE_EXCEL_CONVERTER,

    CONFIG_DEBUG_MODE_F_DATA,

    CONFIG_UI_MODE_TIMEOUT,
};